from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker
from database_setup import *
from flask import json
import json
from random import randint
import datetime
import random
import os

engine = create_engine('postgresql://tourguide:tourGuideLinuxDina@localhost/findYourTourGuide')

Base.metadata.bind = engine

DBSession = sessionmaker(bind=engine)

session = DBSession()

if not session.query(Properties).first():
    prop1 = Properties(propertyName = "description")
    prop2 = Properties(propertyName = "age")
    prop3 = Properties(propertyName = "education")
    prop4 = Properties(propertyName = "certificate")
    prop5 = Properties(propertyName = "gender")
    prop6 = Properties(propertyName = "yearsOfExperience")
    prop7 = Properties(propertyName = "photo")
    session.add(prop1)
    session.add(prop2)
    session.add(prop3)
    session.add(prop4)
    session.add(prop5)
    session.add(prop6)
    session.add(prop7)

    session.commit()


"""if not session.query(Country).first():

    c1 = Country(name = "China")
    session.add(c1)
    c2 = Country(name = "Japan")
    session.add(c2)
    c3 = Country(name = "Thailand")
    session.add(c3)
    c4 = Country(name = "India")
    session.add(c4)
    c5 = Country(name = "Malaysia")
    session.add(c5)
    c6 = Country(name = "Republic of Korea")
    session.add(c6)
    c7 = Country(name = "Hong Kong")
    session.add(c7)
    c8 = Country(name = "Taiwan")
    session.add(c8)
    c9 = Country(name = "Philippines")
    session.add(c9)
    c10 = Country(name = "Australia")
    session.add(c10)
    c11 = Country(name = "Vietnam")
    session.add(c11)
    c12 = Country(name = "Russia")
    session.add(c12)
    c13 = Country(name = "France")
    session.add(c13)
    c14 = Country(name = "Germany")
    session.add(c14)
    c15 = Country(name = "Israel")
    session.add(c15)
    c16 = Country(name = "Sweden")
    session.add(c16)
    c17 = Country(name = "Italy")
    session.add(c17)
    c18 = Country(name = "Netherlands")
    session.add(c18)
    c19 = Country(name = "Greece")
    session.add(c19)
    c20 = Country(name = "Spain")
    session.add(c20)
    c21 = Country(name = "Austria")
    session.add(c21)
    c22 = Country(name = "United Kingdom")
    session.add(c22)
    c23 = Country(name = "Belgium")
    session.add(c23)
    c24 = Country(name = "Portugal")
    session.add(c24)
    c25 = Country(name = "Denmark")
    session.add(c25)
    c26 = Country(name = "Slovenia")
    session.add(c26)
    c27 = Country(name = "Norway")
    session.add(c27)
    c28 = Country(name = "Mexico")
    session.add(c28)
    c29 = Country(name = "Canada")
    session.add(c29)
    c30 = Country(name = "Ukraine")
    session.add(c30)
    c31 = Country(name = "Cyprus")
    session.add(c31)
    c32 = Country(name = "Czech Republic")
    session.add(c32)
    c33 = Country(name = "Switzerland")
    session.add(c33)
    c34 = Country(name = "Romania")
    session.add(c34)
    c35 = Country(name = "Hungary")
    session.add(c35)
    c36 = Country(name = "Georgia")
    session.add(c36)
    c37 = Country(name = "Brazil")
    session.add(c37)
    c38 = Country(name = "Azerbaijan")
    session.add(c38)
    c39 = Country(name = "Slovakia")
    session.add(c39)
    c40 = Country(name = "Serbia")
    session.add(c40)
    c41 = Country(name = "Iceland")
    session.add(c41)
    c42 = Country(name = "Bulgaria")
    session.add(c42)
    c43 = Country(name = "Macedonia")
    session.add(c43)
    c44 = Country(name = "Liechtenstein")
    session.add(c44)
    c45 = Country(name = "Jersey")
    session.add(c45)
    c46 = Country(name = "Poland")
    session.add(c46)
    c47 = Country(name = "Ireland")
    session.add(c47)
    c48 = Country(name = "Croatia")
    session.add(c48)
    c50 = Country(name = "Estonia")
    session.add(c50)
    c51 = Country(name = "Latvia")
    session.add(c51)
    c52 = Country(name = "Isle of Man")
    session.add(c52)
    c53 = Country(name = "Luxembourg")
    session.add(c53)
    c54 = Country(name = "Armenia")
    session.add(c54)
    c55 = Country(name = "Kenya")
    session.add(c55)
    c56 = Country(name = "Chile")
    session.add(c56)
    c57 = Country(name = "Guadeloupe")
    session.add(c57)
    c58 = Country(name = "Martinique")
    session.add(c58)
    c59 = Country(name = "French Guiana")
    session.add(c59)
    c60 = Country(name = "Dominican Republic")
    session.add(c60)
    c61 = Country(name = "Guam")
    session.add(c61)
    c62 = Country(name = "Puerto Rico")
    session.add(c62)
    c63 = Country(name = "Mongolia")
    session.add(c63)
    c64 = Country(name = "New Zealand")
    session.add(c64)
    c65 = Country(name = "Singapore")
    session.add(c65)
    c66 = Country(name = "Indonesia")
    session.add(c66)
    c67 = Country(name = "Nepal")
    session.add(c67)
    c68 = Country(name = "Papua New Guinea")
    session.add(c68)
    c69 = Country(name = "Panama")
    session.add(c69)
    c70 = Country(name = "Costa Rica")
    session.add(c70)
    c71 = Country(name = "Peru")
    session.add(c71)
    c72 = Country(name = "Belize")
    session.add(c72)
    c73 = Country(name = "Nigeria")
    session.add(c73)
    c74 = Country(name = "Venezuela")
    session.add(c74)
    c75 = Country(name = "Bahamas")
    session.add(c75)
    c76 = Country(name = "Morocco")
    session.add(c76)
    c77 = Country(name = "Colombia")
    session.add(c77)
    c78 = Country(name = "Barbados")
    session.add(c78)
    c79 = Country(name = "Egypt")
    session.add(c79)
    c80 = Country(name = "Argentina")
    session.add(c80)
    c81 = Country(name = "Brunei")
    session.add(c81)
    c82 = Country(name = "Aruba")
    session.add(c82)
    c83 = Country(name = "Bangladesh")
    session.add(c83)
    c84 = Country(name = "Cambodia")
    session.add(c84)
    c85 = Country(name = "Macao")
    session.add(c85)
    c86 = Country(name = "Maldives")
    session.add(c86)
    c87 = Country(name = "Montenegro")
    session.add(c87)
    c88 = Country(name = "Fiji")
    session.add(c88)
    c89 = Country(name = "Bermuda")
    session.add(c89)
    c90 = Country(name = "Ecuador")
    session.add(c90)
    c91 = Country(name = "South Africa")
    session.add(c91)
    c92 = Country(name = "Malta")
    session.add(c92)
    c93 = Country(name = "Tanzania")
    session.add(c93)
    c94 = Country(name = "Zambia")
    session.add(c94)
    c95 = Country(name = "Madagascar")
    session.add(c95)
    c96 = Country(name = "Namibia")
    session.add(c96)
    c97 = Country(name = "Cameroon")
    session.add(c97)
    c98 = Country(name = "Malawi")
    session.add(c98)
    c99 = Country(name = "Greenland")
    session.add(c99)
    c100 = Country(name = "Cayman Islands")
    session.add(c100)
    c101 = Country(name = "Jamaica")
    session.add(c101)
    c102 = Country(name = "Monaco")
    session.add(c102)
    c103 = Country(name = "Paraguay")
    session.add(c103)
    c104 = Country(name = "Nicaragua")
    session.add(c104)
    c105 = Country(name = "El Salvador")
    session.add(c105)
    c106 = Country(name = "Andorra")
    session.add(c106)     
    c108 = Country(name = "Sri Lanka")
    session.add(c108)
    c109 = Country(name = "Haiti")
    session.add(c109)
    c110 = Country(name = "Uruguay")
    session.add(c110)
    c111 = Country(name = "Cuba")
    session.add(c111)
    c112 = Country(name = "Ethiopia")
    session.add(c112)
    c113 = Country(name = "United States")
    session.add(c113)

    session.commit()

if not session.query(Cities).first():
    print('I am creating cities')
    countries = session.query(Country).all()
    full_path_to_secrets_file = os.path.join('/var/www/tourGuide/tourGuide/', 'countriesToCitiesNew.JSON')
    countriesToCities = json.loads(open(full_path_to_secrets_file, 'r').read())
    for c in countries:
        country = session.query(Country).filter(Country.name == c.name).one()
        for city in countriesToCities[c.name]:
            newCity = Cities(countryId = country.id , city = city)
            session.add(newCity)
            session.commit()
        print('finish %s' %c.name)"""
